name       : python-autobahn
version    : 23.6.2
release    : 11
source     :
    - https://github.com/crossbario/autobahn-python/archive/refs/tags/v23.6.2.tar.gz : 37eb7566b6257e4589e5ea25a1995c8d2b33d421cd15f6fa2a6b47ec33652d75
homepage   : https://github.com/crossbario/autobahn-python
license    : MIT
component  : programming.python
summary    : Real-time framework for Web, Mobile & Internet of Things
description: |
    Autobahn|Python is a subproject of Autobahn and provides open-source implementations of "The WebSocket Protocol" and "The Web Application Messaging Protocol (WAMP)", for Python 3.7+ and running on Twisted and asyncio.
builddeps  :
    - pkgconfig(python3)
    - python-twisted
    - python-txaio
rundeps    :
    - python-twisted
    - python-txaio
setup      : |
    %python3_setup
install    : |
    %python3_install
