name       : python-autobahn
version    : 21.3.1
release    : 4
source     :
    - https://github.com/crossbario/autobahn-python/archive/refs/tags/v21.3.1.tar.gz : 58f73ee763c0c622f2e1436cca5ae0b5252b920c988e29d82688323919c90d75
license    : MIT
component  : programming.python
summary    : Real-time framework for Web, Mobile & Internet of Things
description: |
    Real-time framework for Web, Mobile & Internet of Things
builddeps  :
    - python-twisted
    - python-six
    - python-txaio
rundeps    :
    - python-twisted
    - python-six
    - python-txaio
setup      : |
    %python3_setup
install    : |
    %python3_install
