name       : python-autobahn
version    : 22.4.2
release    : 9
source     :
    - https://github.com/crossbario/autobahn-python/archive/refs/tags/v22.4.2.tar.gz : f79d912966f31d264a18570b794b953ff243198e6c74984fc04317ddaa2d7ea8
homepage   : https://crossbar.io/autobahn/
license    : MIT
component  : programming.python
summary    : Real-time framework for Web, Mobile & Internet of Things
description: |
    Autobahn|Python is a subproject of Autobahn and provides open-source implementations of "The WebSocket Protocol" and "The Web Application Messaging Protocol (WAMP)", for Python 3.7+ and running on Twisted and asyncio.
builddeps  :
    - pkgconfig(python3)
    - python-twisted
    - python-six
    - python-txaio
rundeps    :
    - python-twisted
    - python-six
    - python-txaio
setup      : |
    %python3_setup
install    : |
    %python3_install
