name       : python-autobahn
version    : 18.6.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/e0/a4/ca655f7fc8cc28274f7415a304e73c525b203828c164cea22e60207afea0/autobahn-18.6.1.tar.gz : 2f41bfc512ec482044fa8cfa74182118dedd87e03b3494472d9ff1b5a1e27d24
license    : MIT
component  : programming.python
summary    : Real-time framework for Web, Mobile & Internet of Things
description: |
    Real-time framework for Web, Mobile & Internet of Things
builddeps  :
    - python-twisted
    - python-six
    - python-txaio
rundeps    :
    - python-twisted
    - python-six
    - python-txaio
setup      : |
    %python3_setup
install    : |
    %python3_install
